<?php

use Laravel\Folio\Folio;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DashboardController;
use App\Http\Middleware\AuthenMiddleware;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\UserManagementController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\NewsletterController;
use App\Http\Controllers\CRUDController;
use App\Http\Controllers\ViewCartController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Middleware\CustomCheckRole;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\FilterController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\ProductManagementController;
use App\Http\Controllers\VouchersController;
use App\Http\Controllers\ReactController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\LookbookController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\RecentlyProductCrontroller;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\SLiderBagController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\VideoController;
use App\Models\Product;
use App\Models\featured_sections;
use App\Models\SizeChart;

Route::post('/register', [RegisterController::class, 'register']);
Route::post('/login', [LoginController::class, 'login']);
Route::post('/logout', [LoginController::class, 'logout']);
Route::get('/check-auth', [LoginController::class, 'checkAuth']);
Route::get('/section', [SectionController::class, 'getSection']);
Route::post('/subscribe', [NewsletterController::class, 'subscribe']);
Route::get('/slider', [SliderController::class, 'getSlider']);
Route::get('/slider-sale', [SliderController::class, 'getSliderSale']);
Route::get('/products/home', [DashboardController::class, 'getProductView']);
Route::get('/products/bestseller', [DashboardController::class, 'getProductBestseller']);
Route::get('/products/men', [DashboardController::class, 'getProductMen']);
Route::get('/products/women', [DashboardController::class, 'getProductWomen']);
Route::get('/products/new', [DashboardController::class, 'getProductNew']);
Route::get('/products/unisex', [DashboardController::class, 'getProductUnisex']);
Route::get('/products/discount', [DashboardController::class, 'getProductDiscount']);
Route::get('/filter/content/{category}', [FilterController::class, 'filterCount']);
Route::get('/product/view/{id}', [ProductController::class, 'view']);
Route::get('/products/related', [ProductController::class, 'relatedProduct']);
Route::get('/cart', [CartController::class, 'cartView']);
Route::get('/cart/data-view', [CartController::class, 'getCartView']);
Route::post('/add-cart', [CartController::class, 'addcart']);
Route::get('/cart-quantity', [CartController::class, 'getCartQuantity']);
Route::get('/cart/subtotal-total', [CartController::class, 'SubtotalTotal']);
Route::delete('/cart/remove/{id}/{size}/{color}/{quantity}', [CartController::class, 'removeItem']);
Route::put('/cart/update-quantity/{id}', [CartController::class, 'updateQuantity']);
Route::get('/checkout/view', [CheckoutController::class, 'checkoutView']);
Route::get('/checkout/payment', [CheckoutController::class, 'paymentView']);
Route::post('/checkout/process', [CheckoutController::class, 'process']);
Route::post('/check-stock', [ProductController::class, 'checkStock']);
Route::post('/handle/checkout', [CheckoutController::class, 'handlecheckout']);
Route::post('/handle/checkout/vnpay', [CheckoutController::class, 'vnpay']);
Route::get('/blog', [BlogController::class, 'blogView']);
Route::post('/check-voucher', [VouchersController::class, 'handleCheckVoucher']);
Route::post('/remove-voucher', [VouchersController::class, 'handleRemoveVoucher']);
Route::get('/product/bags', [ShopController::class, 'getBag']);
Route::get('/product/hats', [ShopController::class, 'getHat']);
Route::get('/product/shoes', [ShopController::class, 'getShoe']);
Route::get('/product/accessorys', [ShopController::class, 'getAccessory']);
Route::get('/product/clothes', [ShopController::class, 'getClothe']);
Route::get('/recently-products', [RecentlyProductCrontroller::class, 'getRecentlyProducts']);
Route::post('/addToRecently', [RecentlyProductCrontroller::class, 'addToRecently']);
Route::get('/product/recently', [RecentlyProductCrontroller::class, 'getAllRecentlyProducts']);
Route::get('/video', [VideoController::class, 'videoView']);
Route::get('/shop/image', [ShopController::class, 'getShop']);
Route::get('/products/search', [ProductController::class, 'handleSearch']);
Route::get('/products/search-chill', [ProductController::class, 'handleSearchChill']);
Route::get('/size/view', [SizeController::class, 'view']);
Route::get('/slider-bag', [SLiderBagController::class, 'index']);
Route::get('/get-lookbook', [LookbookController::class, 'getLookbook']);
Route::get('/lookbook-view/{id}', [LookbookController::class, 'getLookbookDetail']);
Route::get('/store-info', [StoreController::class, 'storeInfo']);
Route::get('/contact-info', [ContactController::class, 'getContact']);
Route::get('/slider-foryou', [SliderController::class, 'getSliderForyou']);
/////
