<?php

use Laravel\Folio\Folio;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DashboardController;
use App\Http\Middleware\AuthenMiddleware;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\TableController;
use App\Http\Controllers\UserManagementController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\NewsletterController;
use App\Http\Controllers\CRUDController;
use App\Http\Controllers\ViewCartController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Middleware\CustomCheckRole;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DiscountController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\FilterController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\ProductManagementController;
use App\Http\Controllers\VouchersController;
use App\Http\Controllers\ReactController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\LookbookController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\RecentlyProductCrontroller;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\SLiderBagController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\VideoController;
use App\Models\Product;
use App\Models\featured_sections;
use App\Models\SizeChart;

//////// 
Route::prefix('api')->group(function () {
    Route::post('/register', [RegisterController::class, 'register']);
    Route::post('/login', [LoginController::class, 'login']);
    Route::post('/logout', [LoginController::class, 'logout']);
    Route::get('/check-auth', [LoginController::class, 'checkAuth']);
    Route::get('/section', [SectionController::class, 'getSection']);
    Route::post('/subscribe', [NewsletterController::class, 'subscribe']);
    Route::get('/slider', [SliderController::class, 'getSlider']);
    Route::get('/slider-sale', [SliderController::class, 'getSliderSale']);
    Route::get('/products/home', [DashboardController::class, 'getProductView']);
    Route::get('/products/bestseller', [DashboardController::class, 'getProductBestseller']);
    Route::get('/products/men', [DashboardController::class, 'getProductMen']);
    Route::get('/products/women', [DashboardController::class, 'getProductWomen']);
    Route::get('/products/new', [DashboardController::class, 'getProductNew']);
    Route::get('/products/unisex', [DashboardController::class, 'getProductUnisex']);
    Route::get('/products/discount', [DashboardController::class, 'getProductDiscount']);
    Route::get('/filter/content/{category}', [FilterController::class, 'filterCount']);
    Route::get('/product/view/{id}', [ProductController::class, 'view']);
    Route::get('/products/related', [ProductController::class, 'relatedProduct']);
    Route::get('/cart', [CartController::class, 'cartView']);
    Route::get('/cart/data-view', [CartController::class, 'getCartView']);
    Route::post('/add-cart', [CartController::class, 'addcart']);
    Route::get('/cart-quantity', [CartController::class, 'getCartQuantity']);
    Route::get('/cart/subtotal-total', [CartController::class, 'SubtotalTotal']);
    Route::delete('/cart/remove/{id}/{size}/{color}/{quantity}', [CartController::class, 'removeItem']);
    Route::put('/cart/update-quantity/{id}', [CartController::class, 'updateQuantity']);
    Route::get('/checkout/view', [CheckoutController::class, 'checkoutView']);
    Route::get('/checkout/payment', [CheckoutController::class, 'paymentView']);
    Route::post('/checkout/process', [CheckoutController::class, 'process']);
    Route::post('/check-stock', [ProductController::class, 'checkStock']);
    Route::post('/handle/checkout', [CheckoutController::class, 'handlecheckout']);
    Route::post('/handle/checkout/vnpay', [CheckoutController::class, 'vnpay']);
    Route::get('/blog', [BlogController::class, 'blogView']);
    Route::post('/check-voucher', [VouchersController::class, 'handleCheckVoucher']);
    Route::post('/remove-voucher', [VouchersController::class, 'handleRemoveVoucher']);
    Route::get('/product/bags', [ShopController::class, 'getBag']);
    Route::get('/product/hats', [ShopController::class, 'getHat']);
    Route::get('/product/shoes', [ShopController::class, 'getShoe']);
    Route::get('/product/accessorys', [ShopController::class, 'getAccessory']);
    Route::get('/product/clothes', [ShopController::class, 'getClothe']);
    Route::get('/recently-products', [RecentlyProductCrontroller::class, 'getRecentlyProducts']);
    Route::post('/addToRecently', [RecentlyProductCrontroller::class, 'addToRecently']);
    Route::get('/product/recently', [RecentlyProductCrontroller::class, 'getAllRecentlyProducts']);
    Route::get('/video', [VideoController::class, 'videoView']);
    Route::get('/shop/image', [ShopController::class, 'getShop']);
    Route::get('/products/search', [ProductController::class, 'handleSearch']);
    Route::get('/size/view', [SizeController::class, 'view']);
    Route::get('/slider-bag', [SLiderBagController::class, 'index']);
    Route::get('/get-lookbook', [LookbookController::class, 'getLookbook']);
    Route::get('/lookbook-view/{id}', [LookbookController::class, 'getLookbookDetail']);
    Route::get('/store-info', [StoreController::class, 'storeInfo']);
    Route::get('/contact-info', [ContactController::class, 'getContact']);


    /////admin
    Route::middleware(['admin'])->group(function () {
        Route::get('/user', [LoginController::class, 'user']);
        Route::post('/upload/product/file', [AuthController::class, 'uploadFile']);
        Route::post('/upload/product', [AuthController::class, 'upload']);
        Route::get('/products/table', [TableController::class, 'index']);
        Route::delete('/product/delete/{id}', [ProductController::class, 'removeproduct']);
        Route::post('/voucher/upload', [VouchersController::class, 'upload']);
        Route::get('/vouchers/view', [VouchersController::class, 'view']);
        Route::delete('/voucher/delete/{id}', [VouchersController::class, 'removeVoucher']);
        Route::get('/voucher/edit/{id}', [VouchersController::class, 'editVouchersView']);
        Route::post('/voucher/update', [VouchersController::class, 'editVouchers']);
        Route::get('/product/edit/{id}', [CRUDController::class, 'edit']);
        Route::post('/update/product', [CRUDController::class, 'update']);
        Route::post('/section/upload', [SectionController::class, 'HandleUpload']);
        Route::get('/section/view', [SectionController::class, 'view']);
        Route::delete('/section/delete/{id}', [SectionController::class, 'removeSection']);
        Route::get('/section/edit/{id}', [SectionController::class, 'editSectionView']);
        Route::post('/section/update', [SectionController::class, 'editSection']);
        Route::post('/slider/upload', [SliderController::class, 'HandleUpload']);
        Route::get('/slider/view', [SliderController::class, 'sliderEditView']);
        Route::delete('/slider/delete/{id}', [SliderController::class, 'removeSlider']);
        Route::get('/slider/edit/{id}', [SliderController::class, 'editSliderView']);
        Route::post('/slider/update', [SliderController::class, 'handleUpdate']);
        Route::post('/blog/update', [BlogController::class, 'blogUpdate']);
        Route::post('/blog/upload', [BlogController::class, 'blogUpload']);
        Route::get('/blog/view', [BlogController::class, 'blogEditView']);
        Route::get('/blog/edit/{id}', [BlogController::class, 'editBlogView']);
        Route::delete('/blog/delete/{id}', [BlogController::class, 'removeBlog']);
        Route::get('/discount/view', [DiscountController::class, 'view']);
        Route::delete('/discount/delete/{id}', [DiscountController::class, 'delete']);
        Route::get('/discount/edit/{id}', [DiscountController::class, 'discountEdit']);
        Route::post('/discount/update', [DiscountController::class, 'handleUpdate']);
        Route::get('/discount/edit/{id}', [DiscountController::class, 'discountEdit']);
        Route::get('/customers/view', [ProductManagementController::class, 'customertable']);
        Route::delete('/customer/delete/{id}', [ProductManagementController::class, 'customerdelete']);
        Route::get('/orders', [ProductManagementController::class, 'orders']);
        Route::get('/orderdetail/{id}', [ProductManagementController::class, 'orderdetail']);
        Route::get('/users/view', [UserManagementController::class, 'index']);
        Route::delete('/user/delete/{id}', [UserManagementController::class, 'delete']);
        Route::get('/user/edit/{id}', [UserManagementController::class, 'userEdit']);
        Route::post('/user/update', [UserManagementController::class, 'userUpdate']);
        Route::post('/video/upload', [VideoController::class, 'HandleUpload']);
        Route::get('/video/update', [VideoController::class, 'handleUpdate']);
        Route::delete('/video/delete/{id}', [VideoController::class, 'removeVideo']);
        Route::get('/video/edit/{id}', [VideoController::class, 'editVideoView']);
        Route::post('/video/update/handle', [VideoController::class, 'handleEditVideo']);
        Route::post('/shop/upload', [ShopController::class, 'shopUpload']);
        Route::get('/shop/update/view', [ShopController::class, 'shopUpdate']);
        Route::delete('/shop/delete/{id}', [ShopController::class, 'removeShopImg']);
        Route::get('/shop/edit/{id}', [ShopController::class, 'editShopView']);
        Route::post('/shop/update', [ShopController::class, 'handleUpdateShop']);
        Route::post('/size/upload', [SizeController::class, 'HandleUpload']);
        Route::post('/size/update', [SizeController::class, 'handleUpdate']);
        Route::delete('/size/delete/{id}', [SizeController::class, 'remove']);
        Route::get('/size/edit/{id}', [SizeController::class, 'edit']);
        Route::post('/slider-bag/upload', [SLiderBagController::class, 'handleUpload']);
        Route::get('/slider-bag/view', [SLiderBagController::class, 'view']);
        Route::delete('/slider-bag/delete/{id}', [SLiderBagController::class, 'delete']);
        Route::get('/slider-bag/edit/view/{id}', [SLiderBagController::class, 'editSliderBagView']);
        Route::post('/slider-bag/update', [SLiderBagController::class, 'handleUpdate']);
        Route::post('/lookbook/upload', [LookbookController::class, 'handleUpload']);
        Route::get('/lookbook-update/view', [LookbookController::class, 'view']);
        Route::delete('/lookbook/delete/{id}', [LookbookController::class, 'delete']);
        Route::get('/lookbook/edit/{id}', [LookbookController::class, 'editView']);
        Route::post('/lookbook-update', [LookbookController::class, 'handleUpdate']);
        Route::post('/store/upload', [StoreController::class, 'handleUpload']);
        Route::get('/about-view', [StoreController::class, 'view']);
        Route::delete('/about/delete/{id}', [StoreController::class, 'delete']);
        Route::get('/about-edit/{id}', [StoreController::class, 'edit']);
        Route::post('/about/update', [StoreController::class, 'handleUpdate']);
        Route::get('/monthly-sales', [ChartController::class, 'getMonthlySales']);
        Route::get('/top-selling-products', [ChartController::class, 'getTopSellingProducts']);
        Route::post('/contact/upload', [ContactController::class, 'handleUpload']);
        Route::get('/contact-view', [ContactController::class, 'getContactView']);
        Route::delete('/contact/delete/{id}', [ContactController::class, 'delete']);
        Route::get('/contact-edit/{id}', [ContactController::class, 'edit']);
        Route::post('/contact/update', [ContactController::class, 'handleUpdate']);
    });
    /////
});

Route::view('/{any}', 'app')->where('any', '.*');
